### ISSUE TITLE
URI Escaping Error

### ISSUE THREAD

**Issue by sirwolfgang** [davishmcclurg/json_schemer#104]
I am getting an issue running this gem on my machine due to the way the schema path is rebuilt. 
```
URI::InvalidURIError: bad URI(is not URI?): "file:/Users/zane/Dropbox/Mac (2)/Documents/Projects/quiltt/quiltt/config/schemas/connect_settings/plaid.json"
/Users/zane/.rubies/ruby-3.0.3/lib/ruby/3.0.0/uri/rfc3986_parser.rb:67:in `split'
/Users/zane/.rubies/ruby-3.0.3/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
/Users/zane/.rubies/ruby-3.0.3/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
/Users/zane/.gem/ruby/3.0.3/gems/json_schemer-0.2.19/lib/json_schemer.rb:58:in `schema'
/Users/zane/.gem/ruby/3.0.3/gems/activerecord_json_validator-2.0.1/lib/active_record/json_validator/validator.rb:18:in `validate_each'
```

**Comment by davishmcclurg** [comment]
Hi @sirwolfgang—it looks like your issue might be from the unencoded space in your file path:

```
>> URI.parse('/Users/zane/Dropbox/Mac (2)/Documents/Projects/quiltt/quiltt/config/schemas/connect_settings/plaid.json')
/Users/dharsha/.rbenv/versions/3.1.1/lib/ruby/3.1.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "/Users/zane/Dropbox/Mac (2)/Documents/Projects/quiltt/quiltt/config/schemas/connect_settings/plaid.json" (URI::InvalidURIError)
	from /Users/dharsha/.rbenv/versions/3.1.1/lib/ruby/3.1.0/uri/rfc3986_parser.rb:72:in `parse'
	from /Users/dharsha/.rbenv/versions/3.1.1/lib/ruby/3.1.0/uri/common.rb:188:in `parse'
	from (irb):1:in `<main>'
	from bin/console:14:in `<main>'
```

**Comment by davishmcclurg** [comment]
I think you will also need to unescape before the file is read: https://github.com/davishmcclurg/json_schemer/blob/edf7e32f667b9acb3e16381e46649070b97668f5/lib/json_schemer.rb#L49
