### ISSUE TITLE
Add "pathname" gem requirement to the docs

### ISSUE THREAD

**Issue by danfowler** [davishmcclurg/json_schemer#15]
Otherwise...

```
$ ruby bin/validate.rb 
Traceback (most recent call last):
	1: from bin/validate.rb:51:in `<main>'
/Users/dan/.rvm/gems/ruby-2.5.1/gems/json_schemer-0.1.7/lib/json_schemer.rb:36:in `schema': uninitialized constant #<Class:JSONSchemer>::Pathname (NameError)
```

Tanks!

**Comment by davishmcclurg** [comment]
Thanks for the issue. `pathname` is actually part of the Ruby standard library, but you're right that it needs to be explicitly required. I added a line to the readme
